export const styles = {
  main: {
    position: "absolute" as "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    bgcolor: "background.paper",
    borderRadius: "8px",
    boxShadow: 24,
    p: 4,
    width: "560px",
  },
  title: {
    color: "#1A262D",
    font: "Inter",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
  },
  closeIcon: {
    marginLeft: "45px",
    marginTop: "5px",
    width: "9px",
    height: "9px",
  },
  label: {
    color: "#6A7381",
    font: "Inter",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
    marginTop: "20px",
  },
  workspaceSelect: {
    width: "495px",
    borderRadius: "8px",
    height: "40px",
    marginTop: "4px",
  },
  info: {
    color: "#9CA5AF",
    font: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    marginTop: "4px",
  },
  buttons: {
    display: "flex",
    flexDirection: "row-reverse",
    marginTop: "24px",
  },
  submit: { width: "100px", height: "40px", marginLeft: "14px" },
  cancel: { width: "100px", height: "40px" },
};
