export const imageObject = {
  "type": "image",
  "version": "4.4.0",
  "originX": "left",
  "originY": "top",
  "left": -2,
  "top": -2,
  "fill": "rgb(0,0,0)",
  "stroke": null,
  "strokeWidth": 0,
  "strokeDashArray": null,
  "strokeLineCap": "butt",
  "strokeDashOffset": 0,
  "strokeLineJoin": "miter",
  "strokeUniform": false,
  "strokeMiterLimit": 4,
  "scaleX": 1.01,
  "scaleY": 1.01,
  "angle": 0,
  "flipX": false,
  "flipY": false,
  "opacity": 1,
  "shadow": null,
  "visible": true,
  "backgroundColor": "",
  "fillRule": "nonzero",
  "paintFirst": "fill",
  "globalCompositeOperation": "source-over",
  "skewX": 0,
  "skewY": 0,
  "cropX": 0,
  "cropY": 0,
  "id": 709454280301,
  "src": "",
  "crossOrigin": "anonymous",
  "filters": [],
  "bg": true
};

export const textBgObject = {
  "type": "rect",
  "version": "4.4.0",
  "originX": "left",
  "originY": "top",
  "left": -2,
  "top": -2,
  "width": 1000,
  "height": 60,
  "fill": "#ffffff",
  "stroke": null,
  "strokeWidth": 1,
  "strokeDashArray": null,
  "strokeLineCap": "butt",
  "strokeDashOffset": 0,
  "strokeLineJoin": "miter",
  "strokeUniform": false,
  "strokeMiterLimit": 4,
  "scaleX": 1,
  "scaleY": 1,
  "angle": 0,
  "flipX": false,
  "flipY": false,
  "opacity": 0.57,
  "shadow": null,
  "visible": true,
  "backgroundColor": "",
  "fillRule": "nonzero",
  "paintFirst": "fill",
  "globalCompositeOperation": "source-over",
  "skewX": 0,
  "skewY": 0,
  "rx": 0,
  "ry": 0,
  "id": 1333823390676
};

export const textObject =   {
  "type": "i-text",
  "version": "4.4.0",
  "originX": "left",
  "originY": "top",
  "left": 7.65,
  "top": 15.03,
  "width": 384.86,
  "height": 28.25,
  "fill": "#000000",
  "stroke": null,
  "strokeWidth": 1,
  "strokeDashArray": null,
  "strokeLineCap": "butt",
  "strokeDashOffset": 0,
  "strokeLineJoin": "miter",
  "strokeUniform": false,
  "strokeMiterLimit": 4,
  "scaleX": 1,
  "scaleY": 1,
  "angle": 0,
  "flipX": false,
  "flipY": false,
  "opacity": 1,
  "shadow": {
    "color": "rgb(0,0,0)",
    "blur": 0,
    "offsetX": 0,
    "offsetY": 0,
    "affectStroke": false,
    "nonScaling": false
  },
  "visible": true,
  "backgroundColor": "",
  "fillRule": "nonzero",
  "paintFirst": "fill",
  "globalCompositeOperation": "source-over",
  "skewX": 0,
  "skewY": 0,
  "text": "",
  "fontSize": 25,
  "fontWeight": "normal",
  "fontFamily": "Arial",
  "fontStyle": "normal",
  "lineHeight": 1.16,
  "underline": false,
  "overline": false,
  "linethrough": false,
  "textAlign": "left",
  "textBackgroundColor": "",
  "charSpacing": 0,
  "path": null,
  "id": 1537860501094
};

export const avatarObject = {
  "type": "avatar",
  "version": 2,
  "originX": "left",
  "originY": "top",
  "left": 472.72,
  "top": 199.28,
  "width": 0,
  "height": 0,
  "fill": "#4868FF",
  "stroke": null,
  "strokeWidth": 0,
  "strokeDashArray": null,
  "strokeLineCap": "butt",
  "strokeDashOffset": 0,
  "strokeLineJoin": "miter",
  "strokeUniform": false,
  "strokeMiterLimit": 4,
  "scaleX": 0.15,
  "scaleY": 0.15,
  "angle": 0,
  "flipX": false,
  "flipY": false,
  "opacity": 1,
  "shadow": null,
  "visible": true,
  "backgroundColor": "",
  "fillRule": "nonzero",
  "paintFirst": "fill",
  "globalCompositeOperation": "source-over",
  "skewX": 0,
  "skewY": 0,
  "cropX": 0,
  "cropY": 0,
  "src": "https://elai-avatars.s3.us-east-2.amazonaws.com/common/amanda/amanda_business_low.png",
  "crossOrigin": null,
  "filters": [],
  "avatarType": "transparent",
  "animation": {
    "type": null
  }
};

export const slideObject = {
  "id": null,
  "speech": "",
  "avatar": {
    "id": "amanda.business",
    "name": "Business",
    "version": 2,
    "gender": "female",
    "canvas": "https://elai-avatars.s3.us-east-2.amazonaws.com/common/amanda/amanda_business_low.png",
  },
  "language": "English",
  "voice": "en-US-AriaNeural",
  "voiceProvider": "azure",
  "voiceType": "text",
  "animation": "fade_in",
  "canvas": {
    "version": "4.4.0",
    "objects": [],
    "background": "#FFFFFF"
  }
};

export const payload = {
  "name": "Waipify Video",
  "slides": [],
  "tags": [],
  "public": false,
  "data": {
    "format": "16_9",
    "musicVolume": 0.2,
    "musicName": "Stay With Me",
    "musicUrl": "https://elai-media.s3.eu-west-2.amazonaws.com/music/mixkit-stay-with-me-838.mp3",
    "resolution": "FullHD"
  }
};
