export type RegistrationFormData = {
  firstName: string;
  lastName: string;
  email: string;
  billingInfo?: BillingInfo;
  companyName: string;
  companyWebsite: string;
  organisationId: string;
  phoneNumber: string;
  termsAgreement: boolean;
  marketingConsent: boolean;
  country: string;
  industry: Industry;
  country_id: string;
  industry_id: string;
  locale_id?: string;
};

export type OrganisationDetailsFormData = {
  firstName: string | null;
  lastName: string | null;
  companyName: string;
  email: string;
  companyWebsite?: string;
  addressLine1: string;
  addressLine2: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  taxId: string | null;
  industry: Industry;
};

export interface OrganisationDetailsFormDto
  extends OrganisationDetailsFormData {
  tenantId: string;
  id: string | null | undefined;
}

export type Address = {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  postalCode: string;
};

export type BillingInfo = {
  billingAddress: Address;
  taxId?: string;
};

export enum Industry {
  real_estate_property = "real_estate_property",
  retail_consumer_products = "retail_consumer_products",
  accounting = "accounting",
  administration_office_support = "administration_office_support",
  advertising_arts_media = "advertising_arts_media",
  banking_financial_services = "banking_financial_services",
  call_centre_customer_service = "call_centre_customer_service",
  community_services_development = "community_services_development",
  construction = "construction",
  consulting_strategy = "consulting_strategy",
  design_architechture = "design_architechture",
  education_training = "education_training",
  engineering = "engineering",
  farming_animals_conservation = "farming_animals_conservation",
  government_defence = "government_defence",
  healthcare_medical = "healthcare_medical",
  hospitality_tourism = "hospitality_tourism",
  human_resources_recruitment = "human_resources_recruitment",
  information_communication_technology = "information_communication_technology",
  insurance = "insurance",
  legal = "legal",
  manufacturing_transport_logistics = "manufacturing_transport_logistics",
  marketing_communications = "marketing_communications",
  mining_resources_energy = "mining_resources_energy",
  sales = "sales",
  science_technology = "science_technology",
  sport_recreation = "sport_recreation",
  trades_services = "trades_services",
  other = "other",
  not_selected = "not_selected",
}

export function getLocalizedCountries(locale: string): Array<LocalizedCountry> {
  return COUNTRIES.map((country) => {
    let name: string;
    switch (locale) {
      case "en-US": {
        name = country.en;
        break;
      }
      case "de-DE": {
        name = country.de;
        break;
      }
      case "es-ES": {
        name = country.es;
        break;
      }
      default: {
        name = country.en;
      }
    }
    return { name, flag: country.flag, iso2: country.iso2 };
  }).sort((c1, c2) => c1.name.localeCompare(c2.name, locale));
}

export type LocalizedCountry = {
  name: string;
  iso2: string;
  flag: string;
};

export type Country = {
  en: string;
  iso2: string;
  iso3: string;
  flag: string;
  de: string;
  es: string;
};

export const COUNTRIES: Array<Country> = [
  {
    de: "Aruba",
    es: "Aruba",
    en: "Aruba",
    flag: "🇦🇼",
    iso2: "AW",
    iso3: "ABW",
  },
  {
    de: "Afghanistan",
    es: "Afganistán",
    en: "Afghanistan",
    flag: "🇦🇫",
    iso2: "AF",
    iso3: "AFG",
  },
  {
    de: "Angola",
    es: "Angola",
    en: "Angola",
    flag: "🇦🇴",
    iso2: "AO",
    iso3: "AGO",
  },
  {
    de: "Anguilla",
    es: "Anguilla",
    en: "Anguilla",
    flag: "🇦🇮",
    iso2: "AI",
    iso3: "AIA",
  },
  {
    de: "Åland",
    es: "Alandia",
    en: "Åland Islands",
    flag: "🇦🇽",
    iso2: "AX",
    iso3: "ALA",
  },
  {
    de: "Albanien",
    es: "Albania",
    en: "Albania",
    flag: "🇦🇱",
    iso2: "AL",
    iso3: "ALB",
  },
  {
    de: "Andorra",
    es: "Andorra",
    en: "Andorra",
    flag: "🇦🇩",
    iso2: "AD",
    iso3: "AND",
  },
  {
    de: "Vereinigte Arabische Emirate",
    es: "Emiratos Árabes Unidos",
    en: "United Arab Emirates",
    flag: "🇦🇪",
    iso2: "AE",
    iso3: "ARE",
  },
  {
    de: "Argentinien",
    es: "Argentina",
    en: "Argentina",
    flag: "🇦🇷",
    iso2: "AR",
    iso3: "ARG",
  },
  {
    de: "Armenien",
    es: "Armenia",
    en: "Armenia",
    flag: "🇦🇲",
    iso2: "AM",
    iso3: "ARM",
  },
  {
    de: "Amerikanisch-Samoa",
    es: "Samoa Americana",
    en: "American Samoa",
    flag: "🇦🇸",
    iso2: "AS",
    iso3: "ASM",
  },
  {
    de: "Antarktis",
    es: "Antártida",
    en: "Antarctica",
    flag: "🇦🇶",
    iso2: "AQ",
    iso3: "ATA",
  },
  {
    de: "Französische Süd- und Antarktisgebiete",
    es: "Tierras Australes y Antárticas Francesas",
    en: "French Southern and Antarctic Lands",
    flag: "🇹🇫",
    iso2: "TF",
    iso3: "ATF",
  },
  {
    de: "Antigua und Barbuda",
    es: "Antigua y Barbuda",
    en: "Antigua and Barbuda",
    flag: "🇦🇬",
    iso2: "AG",
    iso3: "ATG",
  },
  {
    de: "Australien",
    es: "Australia",
    en: "Australia",
    flag: "🇦🇺",
    iso2: "AU",
    iso3: "AUS",
  },
  {
    de: "Österreich",
    es: "Austria",
    en: "Austria",
    flag: "🇦🇹",
    iso2: "AT",
    iso3: "AUT",
  },
  {
    de: "Aserbaidschan",
    es: "Azerbaiyán",
    en: "Azerbaijan",
    flag: "🇦🇿",
    iso2: "AZ",
    iso3: "AZE",
  },
  {
    de: "Burundi",
    es: "Burundi",
    en: "Burundi",
    flag: "🇧🇮",
    iso2: "BI",
    iso3: "BDI",
  },
  {
    de: "Belgien",
    es: "Bélgica",
    en: "Belgium",
    flag: "🇧🇪",
    iso2: "BE",
    iso3: "BEL",
  },
  {
    de: "Benin",
    es: "Benín",
    en: "Benin",
    flag: "🇧🇯",
    iso2: "BJ",
    iso3: "BEN",
  },
  {
    de: "Burkina Faso",
    es: "Burkina Faso",
    en: "Burkina Faso",
    flag: "🇧🇫",
    iso2: "BF",
    iso3: "BFA",
  },
  {
    de: "Bangladesch",
    es: "Bangladesh",
    en: "Bangladesh",
    flag: "🇧🇩",
    iso2: "BD",
    iso3: "BGD",
  },
  {
    de: "Bulgarien",
    es: "Bulgaria",
    en: "Bulgaria",
    flag: "🇧🇬",
    iso2: "BG",
    iso3: "BGR",
  },
  {
    de: "Bahrain",
    es: "Bahrein",
    en: "Bahrain",
    flag: "🇧🇭",
    iso2: "BH",
    iso3: "BHR",
  },
  {
    de: "Bahamas",
    es: "Bahamas",
    en: "Bahamas",
    flag: "🇧🇸",
    iso2: "BS",
    iso3: "BHS",
  },
  {
    de: "Bosnien und Herzegowina",
    es: "Bosnia y Herzegovina",
    en: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    iso2: "BA",
    iso3: "BIH",
  },
  {
    de: "Saint-Barthélemy",
    es: "San Bartolomé",
    en: "Saint Barthélemy",
    flag: "🇧🇱",
    iso2: "BL",
    iso3: "BLM",
  },
  {
    de: "St. Helena, Ascension und Tristan da Cunha",
    es: "Santa Elena, Ascensión y Tristán de Acuña",
    en: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "🇸🇭",
    iso2: "SH",
    iso3: "SHN",
  },
  {
    de: "Weißrussland",
    es: "Bielorrusia",
    en: "Belarus",
    flag: "🇧🇾",
    iso2: "BY",
    iso3: "BLR",
  },
  {
    de: "Belize",
    es: "Belice",
    en: "Belize",
    flag: "🇧🇿",
    iso2: "BZ",
    iso3: "BLZ",
  },
  {
    de: "Bermuda",
    es: "Bermudas",
    en: "Bermuda",
    flag: "🇧🇲",
    iso2: "BM",
    iso3: "BMU",
  },
  {
    de: "Bolivien",
    es: "Bolivia",
    en: "Bolivia",
    flag: "🇧🇴",
    iso2: "BO",
    iso3: "BOL",
  },
  {
    de: "Karibische Niederlande",
    es: "Caribe Neerlandés",
    en: "Caribbean Netherlands",
    flag: "",
    iso2: "BQ",
    iso3: "BES",
  },
  {
    de: "Brasilien",
    es: "Brasil",
    en: "Brazil",
    flag: "🇧🇷",
    iso2: "BR",
    iso3: "BRA",
  },
  {
    de: "Barbados",
    es: "Barbados",
    en: "Barbados",
    flag: "🇧🇧",
    iso2: "BB",
    iso3: "BRB",
  },
  {
    de: "Brunei",
    es: "Brunei",
    en: "Brunei",
    flag: "🇧🇳",
    iso2: "BN",
    iso3: "BRN",
  },
  {
    de: "Bhutan",
    es: "Bután",
    en: "Bhutan",
    flag: "🇧🇹",
    iso2: "BT",
    iso3: "BTN",
  },
  {
    de: "Bouvetinsel",
    es: "Isla Bouvet",
    en: "Bouvet Island",
    flag: "🇧🇻",
    iso2: "BV",
    iso3: "BVT",
  },
  {
    de: "Botswana",
    es: "Botswana",
    en: "Botswana",
    flag: "🇧🇼",
    iso2: "BW",
    iso3: "BWA",
  },
  {
    de: "Zentralafrikanische Republik",
    es: "República Centroafricana",
    en: "Central African Republic",
    flag: "🇨🇫",
    iso2: "CF",
    iso3: "CAF",
  },
  {
    de: "Kanada",
    es: "Canadá",
    en: "Canada",
    flag: "🇨🇦",
    iso2: "CA",
    iso3: "CAN",
  },
  {
    de: "Kokosinseln",
    es: "Islas Cocos o Islas Keeling",
    en: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
    iso2: "CC",
    iso3: "CCK",
  },
  {
    de: "Schweiz",
    es: "Suiza",
    en: "Switzerland",
    flag: "🇨🇭",
    iso2: "CH",
    iso3: "CHE",
  },
  {
    de: "Chile",
    es: "Chile",
    en: "Chile",
    flag: "🇨🇱",
    iso2: "CL",
    iso3: "CHL",
  },
  {
    de: "China",
    es: "China",
    en: "China",
    flag: "🇨🇳",
    iso2: "CN",
    iso3: "CHN",
  },
  {
    de: "Elfenbeinküste",
    es: "Costa de Marfil",
    en: "Ivory Coast",
    flag: "🇨🇮",
    iso2: "CI",
    iso3: "CIV",
  },
  {
    de: "Kamerun",
    es: "Camerún",
    en: "Cameroon",
    flag: "🇨🇲",
    iso2: "CM",
    iso3: "CMR",
  },
  {
    de: "Kongo (Dem. Rep.)",
    es: "Congo (Rep. Dem.)",
    en: "DR Congo",
    flag: "🇨🇩",
    iso2: "CD",
    iso3: "COD",
  },
  {
    de: "Kongo",
    es: "Congo",
    en: "Republic of the Congo",
    flag: "🇨🇬",
    iso2: "CG",
    iso3: "COG",
  },
  {
    de: "Cookinseln",
    es: "Islas Cook",
    en: "Cook Islands",
    flag: "🇨🇰",
    iso2: "CK",
    iso3: "COK",
  },
  {
    de: "Kolumbien",
    es: "Colombia",
    en: "Colombia",
    flag: "🇨🇴",
    iso2: "CO",
    iso3: "COL",
  },
  {
    de: "Komoren",
    es: "Comoras",
    en: "Comoros",
    flag: "🇰🇲",
    iso2: "KM",
    iso3: "COM",
  },
  {
    de: "Kap Verde",
    es: "Cabo Verde",
    en: "Cape Verde",
    flag: "🇨🇻",
    iso2: "CV",
    iso3: "CPV",
  },
  {
    de: "Costa Rica",
    es: "Costa Rica",
    en: "Costa Rica",
    flag: "🇨🇷",
    iso2: "CR",
    iso3: "CRI",
  },
  {
    de: "Kuba",
    es: "Cuba",
    en: "Cuba",
    flag: "🇨🇺",
    iso2: "CU",
    iso3: "CUB",
  },
  {
    de: "Curaçao",
    es: "Curazao",
    en: "Curaçao",
    flag: "🇨🇼",
    iso2: "CW",
    iso3: "CUW",
  },
  {
    de: "Weihnachtsinsel",
    es: "Isla de Navidad",
    en: "Christmas Island",
    flag: "🇨🇽",
    iso2: "CX",
    iso3: "CXR",
  },
  {
    de: "Kaimaninseln",
    es: "Islas Caimán",
    en: "Cayman Islands",
    flag: "🇰🇾",
    iso2: "KY",
    iso3: "CYM",
  },
  {
    de: "Zypern",
    es: "Chipre",
    en: "Cyprus",
    flag: "🇨🇾",
    iso2: "CY",
    iso3: "CYP",
  },
  {
    de: "Tschechien",
    es: "Chequia",
    en: "Czechia",
    flag: "🇨🇿",
    iso2: "CZ",
    iso3: "CZE",
  },
  {
    de: "Deutschland",
    es: "Alemania",
    en: "Germany",
    flag: "🇩🇪",
    iso2: "DE",
    iso3: "DEU",
  },
  {
    de: "Dschibuti",
    es: "Djibouti",
    en: "Djibouti",
    flag: "🇩🇯",
    iso2: "DJ",
    iso3: "DJI",
  },
  {
    de: "Dominica",
    es: "Dominica",
    en: "Dominica",
    flag: "🇩🇲",
    iso2: "DM",
    iso3: "DMA",
  },
  {
    de: "Dänemark",
    es: "Dinamarca",
    en: "Denmark",
    flag: "🇩🇰",
    iso2: "DK",
    iso3: "DNK",
  },
  {
    de: "Dominikanische Republik",
    es: "República Dominicana",
    en: "Dominican Republic",
    flag: "🇩🇴",
    iso2: "DO",
    iso3: "DOM",
  },
  {
    de: "Algerien",
    es: "Argelia",
    en: "Algeria",
    flag: "🇩🇿",
    iso2: "DZ",
    iso3: "DZA",
  },
  {
    de: "Ecuador",
    es: "Ecuador",
    en: "Ecuador",
    flag: "🇪🇨",
    iso2: "EC",
    iso3: "ECU",
  },
  {
    de: "Ägypten",
    es: "Egipto",
    en: "Egypt",
    flag: "🇪🇬",
    iso2: "EG",
    iso3: "EGY",
  },
  {
    de: "Eritrea",
    es: "Eritrea",
    en: "Eritrea",
    flag: "🇪🇷",
    iso2: "ER",
    iso3: "ERI",
  },
  {
    de: "Westsahara",
    es: "Sahara Occidental",
    en: "Western Sahara",
    flag: "🇪🇭",
    iso2: "EH",
    iso3: "ESH",
  },
  {
    de: "Spanien",
    es: "España",
    en: "Spain",
    flag: "🇪🇸",
    iso2: "ES",
    iso3: "ESP",
  },
  {
    de: "Estland",
    es: "Estonia",
    en: "Estonia",
    flag: "🇪🇪",
    iso2: "EE",
    iso3: "EST",
  },
  {
    de: "Äthiopien",
    es: "Etiopía",
    en: "Ethiopia",
    flag: "🇪🇹",
    iso2: "ET",
    iso3: "ETH",
  },
  {
    de: "Finnland",
    es: "Finlandia",
    en: "Finland",
    flag: "🇫🇮",
    iso2: "FI",
    iso3: "FIN",
  },
  {
    de: "Fidschi",
    es: "Fiyi",
    en: "Fiji",
    flag: "🇫🇯",
    iso2: "FJ",
    iso3: "FJI",
  },
  {
    de: "Falklandinseln",
    es: "Islas Malvinas",
    en: "Falkland Islands",
    flag: "🇫🇰",
    iso2: "FK",
    iso3: "FLK",
  },
  {
    de: "Frankreich",
    es: "Francia",
    en: "France",
    flag: "🇫🇷",
    iso2: "FR",
    iso3: "FRA",
  },
  {
    de: "Färöer-Inseln",
    es: "Islas Faroe",
    en: "Faroe Islands",
    flag: "🇫🇴",
    iso2: "FO",
    iso3: "FRO",
  },
  {
    de: "Mikronesien",
    es: "Micronesia",
    en: "Micronesia",
    flag: "🇫🇲",
    iso2: "FM",
    iso3: "FSM",
  },
  {
    de: "Gabun",
    es: "Gabón",
    en: "Gabon",
    flag: "🇬🇦",
    iso2: "GA",
    iso3: "GAB",
  },
  {
    de: "Vereinigtes Königreich",
    es: "Reino Unido",
    en: "United Kingdom",
    flag: "🇬🇧",
    iso2: "GB",
    iso3: "GBR",
  },
  {
    de: "Georgien",
    es: "Georgia",
    en: "Georgia",
    flag: "🇬🇪",
    iso2: "GE",
    iso3: "GEO",
  },
  {
    de: "Guernsey",
    es: "Guernsey",
    en: "Guernsey",
    flag: "🇬🇬",
    iso2: "GG",
    iso3: "GGY",
  },
  {
    de: "Ghana",
    es: "Ghana",
    en: "Ghana",
    flag: "🇬🇭",
    iso2: "GH",
    iso3: "GHA",
  },
  {
    de: "Gibraltar",
    es: "Gibraltar",
    en: "Gibraltar",
    flag: "🇬🇮",
    iso2: "GI",
    iso3: "GIB",
  },
  {
    de: "Guinea",
    es: "Guinea",
    en: "Guinea",
    flag: "🇬🇳",
    iso2: "GN",
    iso3: "GIN",
  },
  {
    de: "Guadeloupe",
    es: "Guadalupe",
    en: "Guadeloupe",
    flag: "🇬🇵",
    iso2: "GP",
    iso3: "GLP",
  },
  {
    de: "Gambia",
    es: "Gambia",
    en: "Gambia",
    flag: "🇬🇲",
    iso2: "GM",
    iso3: "GMB",
  },
  {
    de: "Guinea-Bissau",
    es: "Guinea-Bisáu",
    en: "Guinea-Bissau",
    flag: "🇬🇼",
    iso2: "GW",
    iso3: "GNB",
  },
  {
    de: "Äquatorialguinea",
    es: "Guinea Ecuatorial",
    en: "Equatorial Guinea",
    flag: "🇬🇶",
    iso2: "GQ",
    iso3: "GNQ",
  },
  {
    de: "Griechenland",
    es: "Grecia",
    en: "Greece",
    flag: "🇬🇷",
    iso2: "GR",
    iso3: "GRC",
  },
  {
    de: "Grenada",
    es: "Grenada",
    en: "Grenada",
    flag: "🇬🇩",
    iso2: "GD",
    iso3: "GRD",
  },
  {
    de: "Grönland",
    es: "Groenlandia",
    en: "Greenland",
    flag: "🇬🇱",
    iso2: "GL",
    iso3: "GRL",
  },
  {
    de: "Guatemala",
    es: "Guatemala",
    en: "Guatemala",
    flag: "🇬🇹",
    iso2: "GT",
    iso3: "GTM",
  },
  {
    de: "Französisch-Guayana",
    es: "Guayana Francesa",
    en: "French Guiana",
    flag: "🇬🇫",
    iso2: "GF",
    iso3: "GUF",
  },
  {
    de: "Guam",
    es: "Guam",
    en: "Guam",
    flag: "🇬🇺",
    iso2: "GU",
    iso3: "GUM",
  },
  {
    de: "Guyana",
    es: "Guyana",
    en: "Guyana",
    flag: "🇬🇾",
    iso2: "GY",
    iso3: "GUY",
  },
  {
    de: "Hongkong",
    es: "Hong Kong",
    en: "Hong Kong",
    flag: "🇭🇰",
    iso2: "HK",
    iso3: "HKG",
  },
  {
    de: "Heard und die McDonaldinseln",
    es: "Islas Heard y McDonald",
    en: "Heard Island and McDonald Islands",
    flag: "🇭🇲",
    iso2: "HM",
    iso3: "HMD",
  },
  {
    de: "Honduras",
    es: "Honduras",
    en: "Honduras",
    flag: "🇭🇳",
    iso2: "HN",
    iso3: "HND",
  },
  {
    de: "Kroatien",
    es: "Croacia",
    en: "Croatia",
    flag: "🇭🇷",
    iso2: "HR",
    iso3: "HRV",
  },
  {
    de: "Haiti",
    es: "Haití",
    en: "Haiti",
    flag: "🇭🇹",
    iso2: "HT",
    iso3: "HTI",
  },
  {
    de: "Ungarn",
    es: "Hungría",
    en: "Hungary",
    flag: "🇭🇺",
    iso2: "HU",
    iso3: "HUN",
  },
  {
    de: "Indonesien",
    es: "Indonesia",
    en: "Indonesia",
    flag: "🇮🇩",
    iso2: "ID",
    iso3: "IDN",
  },
  {
    de: "Insel Man",
    es: "Isla de Man",
    en: "Isle of Man",
    flag: "🇮🇲",
    iso2: "IM",
    iso3: "IMN",
  },
  {
    de: "Indien",
    es: "India",
    en: "India",
    flag: "🇮🇳",
    iso2: "IN",
    iso3: "IND",
  },
  {
    de: "Britisches Territorium im Indischen Ozean",
    es: "Territorio Británico del Océano Índico",
    en: "British Indian Ocean Territory",
    flag: "🇮🇴",
    iso2: "IO",
    iso3: "IOT",
  },
  {
    de: "Irland",
    es: "Irlanda",
    en: "Ireland",
    flag: "🇮🇪",
    iso2: "IE",
    iso3: "IRL",
  },
  {
    de: "Iran",
    es: "Iran",
    en: "Iran",
    flag: "🇮🇷",
    iso2: "IR",
    iso3: "IRN",
  },
  {
    de: "Irak",
    es: "Irak",
    en: "Iraq",
    flag: "🇮🇶",
    iso2: "IQ",
    iso3: "IRQ",
  },
  {
    de: "Island",
    es: "Islandia",
    en: "Iceland",
    flag: "🇮🇸",
    iso2: "IS",
    iso3: "ISL",
  },
  {
    de: "Israel",
    es: "Israel",
    en: "Israel",
    flag: "🇮🇱",
    iso2: "IL",
    iso3: "ISR",
  },
  {
    de: "Italien",
    es: "Italia",
    en: "Italy",
    flag: "🇮🇹",
    iso2: "IT",
    iso3: "ITA",
  },
  {
    de: "Jamaika",
    es: "Jamaica",
    en: "Jamaica",
    flag: "🇯🇲",
    iso2: "JM",
    iso3: "JAM",
  },
  {
    de: "Jersey",
    es: "Jersey",
    en: "Jersey",
    flag: "🇯🇪",
    iso2: "JE",
    iso3: "JEY",
  },
  {
    de: "Jordanien",
    es: "Jordania",
    en: "Jordan",
    flag: "🇯🇴",
    iso2: "JO",
    iso3: "JOR",
  },
  {
    de: "Japan",
    es: "Japón",
    en: "Japan",
    flag: "🇯🇵",
    iso2: "JP",
    iso3: "JPN",
  },
  {
    de: "Kasachstan",
    es: "Kazajistán",
    en: "Kazakhstan",
    flag: "🇰🇿",
    iso2: "KZ",
    iso3: "KAZ",
  },
  {
    de: "Kenia",
    es: "Kenia",
    en: "Kenya",
    flag: "🇰🇪",
    iso2: "KE",
    iso3: "KEN",
  },
  {
    de: "Kirgisistan",
    es: "Kirguizistán",
    en: "Kyrgyzstan",
    flag: "🇰🇬",
    iso2: "KG",
    iso3: "KGZ",
  },
  {
    de: "Kambodscha",
    es: "Camboya",
    en: "Cambodia",
    flag: "🇰🇭",
    iso2: "KH",
    iso3: "KHM",
  },
  {
    de: "Kiribati",
    es: "Kiribati",
    en: "Kiribati",
    flag: "🇰🇮",
    iso2: "KI",
    iso3: "KIR",
  },
  {
    de: "St. Kitts und Nevis",
    es: "San Cristóbal y Nieves",
    en: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    iso2: "KN",
    iso3: "KNA",
  },
  {
    de: "Südkorea",
    es: "Corea del Sur",
    en: "South Korea",
    flag: "🇰🇷",
    iso2: "KR",
    iso3: "KOR",
  },
  {
    de: "Kosovo",
    es: "Kosovo",
    en: "Kosovo",
    flag: "🇽🇰",
    iso2: "XK",
    iso3: "UNK",
  },
  {
    de: "Kuwait",
    es: "Kuwait",
    en: "Kuwait",
    flag: "🇰🇼",
    iso2: "KW",
    iso3: "KWT",
  },
  {
    de: "Laos",
    es: "Laos",
    en: "Laos",
    flag: "🇱🇦",
    iso2: "LA",
    iso3: "LAO",
  },
  {
    de: "Libanon",
    es: "Líbano",
    en: "Lebanon",
    flag: "🇱🇧",
    iso2: "LB",
    iso3: "LBN",
  },
  {
    de: "Liberia",
    es: "Liberia",
    en: "Liberia",
    flag: "🇱🇷",
    iso2: "LR",
    iso3: "LBR",
  },
  {
    de: "Libyen",
    es: "Libia",
    en: "Libya",
    flag: "🇱🇾",
    iso2: "LY",
    iso3: "LBY",
  },
  {
    de: "St. Lucia",
    es: "Santa Lucía",
    en: "Saint Lucia",
    flag: "🇱🇨",
    iso2: "LC",
    iso3: "LCA",
  },
  {
    de: "Liechtenstein",
    es: "Liechtenstein",
    en: "Liechtenstein",
    flag: "🇱🇮",
    iso2: "LI",
    iso3: "LIE",
  },
  {
    de: "Sri Lanka",
    es: "Sri Lanka",
    en: "Sri Lanka",
    flag: "🇱🇰",
    iso2: "LK",
    iso3: "LKA",
  },
  {
    de: "Lesotho",
    es: "Lesotho",
    en: "Lesotho",
    flag: "🇱🇸",
    iso2: "LS",
    iso3: "LSO",
  },
  {
    de: "Litauen",
    es: "Lituania",
    en: "Lithuania",
    flag: "🇱🇹",
    iso2: "LT",
    iso3: "LTU",
  },
  {
    de: "Luxemburg",
    es: "Luxemburgo",
    en: "Luxembourg",
    flag: "🇱🇺",
    iso2: "LU",
    iso3: "LUX",
  },
  {
    de: "Lettland",
    es: "Letonia",
    en: "Latvia",
    flag: "🇱🇻",
    iso2: "LV",
    iso3: "LVA",
  },
  {
    de: "Macao",
    es: "Macao",
    en: "Macau",
    flag: "🇲🇴",
    iso2: "MO",
    iso3: "MAC",
  },
  {
    de: "Saint-Martin",
    es: "Saint Martin",
    en: "Saint Martin",
    flag: "🇲🇫",
    iso2: "MF",
    iso3: "MAF",
  },
  {
    de: "Marokko",
    es: "Marruecos",
    en: "Morocco",
    flag: "🇲🇦",
    iso2: "MA",
    iso3: "MAR",
  },
  {
    de: "Monaco",
    es: "Mónaco",
    en: "Monaco",
    flag: "🇲🇨",
    iso2: "MC",
    iso3: "MCO",
  },
  {
    de: "Moldawien",
    es: "Moldavia",
    en: "Moldova",
    flag: "🇲🇩",
    iso2: "MD",
    iso3: "MDA",
  },
  {
    de: "Madagaskar",
    es: "Madagascar",
    en: "Madagascar",
    flag: "🇲🇬",
    iso2: "MG",
    iso3: "MDG",
  },
  {
    de: "Malediven",
    es: "Maldivas",
    en: "Maldives",
    flag: "🇲🇻",
    iso2: "MV",
    iso3: "MDV",
  },
  {
    de: "Mexiko",
    es: "México",
    en: "Mexico",
    flag: "🇲🇽",
    iso2: "MX",
    iso3: "MEX",
  },
  {
    de: "Marshallinseln",
    es: "Islas Marshall",
    en: "Marshall Islands",
    flag: "🇲🇭",
    iso2: "MH",
    iso3: "MHL",
  },
  {
    de: "Nordmazedonien",
    es: "Macedonia del Norte",
    en: "North Macedonia",
    flag: "🇲🇰",
    iso2: "MK",
    iso3: "MKD",
  },
  {
    de: "Mali",
    es: "Mali",
    en: "Mali",
    flag: "🇲🇱",
    iso2: "ML",
    iso3: "MLI",
  },
  {
    de: "Malta",
    es: "Malta",
    en: "Malta",
    flag: "🇲🇹",
    iso2: "MT",
    iso3: "MLT",
  },
  {
    de: "Myanmar",
    es: "Myanmar",
    en: "Myanmar",
    flag: "🇲🇲",
    iso2: "MM",
    iso3: "MMR",
  },
  {
    de: "Montenegro",
    es: "Montenegro",
    en: "Montenegro",
    flag: "🇲🇪",
    iso2: "ME",
    iso3: "MNE",
  },
  {
    de: "Mongolei",
    es: "Mongolia",
    en: "Mongolia",
    flag: "🇲🇳",
    iso2: "MN",
    iso3: "MNG",
  },
  {
    de: "Nördliche Marianen",
    es: "Islas Marianas del Norte",
    en: "Northern Mariana Islands",
    flag: "🇲🇵",
    iso2: "MP",
    iso3: "MNP",
  },
  {
    de: "Mosambik",
    es: "Mozambique",
    en: "Mozambique",
    flag: "🇲🇿",
    iso2: "MZ",
    iso3: "MOZ",
  },
  {
    de: "Mauretanien",
    es: "Mauritania",
    en: "Mauritania",
    flag: "🇲🇷",
    iso2: "MR",
    iso3: "MRT",
  },
  {
    de: "Montserrat",
    es: "Montserrat",
    en: "Montserrat",
    flag: "🇲🇸",
    iso2: "MS",
    iso3: "MSR",
  },
  {
    de: "Martinique",
    es: "Martinica",
    en: "Martinique",
    flag: "🇲🇶",
    iso2: "MQ",
    iso3: "MTQ",
  },
  {
    de: "Mauritius",
    es: "Mauricio",
    en: "Mauritius",
    flag: "🇲🇺",
    iso2: "MU",
    iso3: "MUS",
  },
  {
    de: "Malawi",
    es: "Malawi",
    en: "Malawi",
    flag: "🇲🇼",
    iso2: "MW",
    iso3: "MWI",
  },
  {
    de: "Malaysia",
    es: "Malasia",
    en: "Malaysia",
    flag: "🇲🇾",
    iso2: "MY",
    iso3: "MYS",
  },
  {
    de: "Mayotte",
    es: "Mayotte",
    en: "Mayotte",
    flag: "🇾🇹",
    iso2: "YT",
    iso3: "MYT",
  },
  {
    de: "Namibia",
    es: "Namibia",
    en: "Namibia",
    flag: "🇳🇦",
    iso2: "NA",
    iso3: "NAM",
  },
  {
    de: "Neukaledonien",
    es: "Nueva Caledonia",
    en: "New Caledonia",
    flag: "🇳🇨",
    iso2: "NC",
    iso3: "NCL",
  },
  {
    de: "Niger",
    es: "Níger",
    en: "Niger",
    flag: "🇳🇪",
    iso2: "NE",
    iso3: "NER",
  },
  {
    de: "Norfolkinsel",
    es: "Isla de Norfolk",
    en: "Norfolk Island",
    flag: "🇳🇫",
    iso2: "NF",
    iso3: "NFK",
  },
  {
    de: "Nigeria",
    es: "Nigeria",
    en: "Nigeria",
    flag: "🇳🇬",
    iso2: "NG",
    iso3: "NGA",
  },
  {
    de: "Nicaragua",
    es: "Nicaragua",
    en: "Nicaragua",
    flag: "🇳🇮",
    iso2: "NI",
    iso3: "NIC",
  },
  {
    de: "Niue",
    es: "Niue",
    en: "Niue",
    flag: "🇳🇺",
    iso2: "NU",
    iso3: "NIU",
  },
  {
    de: "Niederlande",
    es: "Países Bajos",
    en: "Netherlands",
    flag: "🇳🇱",
    iso2: "NL",
    iso3: "NLD",
  },
  {
    de: "Norwegen",
    es: "Noruega",
    en: "Norway",
    flag: "🇳🇴",
    iso2: "NO",
    iso3: "NOR",
  },
  {
    de: "Nepal",
    es: "Nepal",
    en: "Nepal",
    flag: "🇳🇵",
    iso2: "NP",
    iso3: "NPL",
  },
  {
    de: "Nauru",
    es: "Nauru",
    en: "Nauru",
    flag: "🇳🇷",
    iso2: "NR",
    iso3: "NRU",
  },
  {
    de: "Neuseeland",
    es: "Nueva Zelanda",
    en: "New Zealand",
    flag: "🇳🇿",
    iso2: "NZ",
    iso3: "NZL",
  },
  {
    de: "Oman",
    es: "Omán",
    en: "Oman",
    flag: "🇴🇲",
    iso2: "OM",
    iso3: "OMN",
  },
  {
    de: "Pakistan",
    es: "Pakistán",
    en: "Pakistan",
    flag: "🇵🇰",
    iso2: "PK",
    iso3: "PAK",
  },
  {
    de: "Panama",
    es: "Panamá",
    en: "Panama",
    flag: "🇵🇦",
    iso2: "PA",
    iso3: "PAN",
  },
  {
    de: "Pitcairninseln",
    es: "Islas Pitcairn",
    en: "Pitcairn Islands",
    flag: "🇵🇳",
    iso2: "PN",
    iso3: "PCN",
  },
  {
    de: "Peru",
    es: "Perú",
    en: "Peru",
    flag: "🇵🇪",
    iso2: "PE",
    iso3: "PER",
  },
  {
    de: "Philippinen",
    es: "Filipinas",
    en: "Philippines",
    flag: "🇵🇭",
    iso2: "PH",
    iso3: "PHL",
  },
  {
    de: "Palau",
    es: "Palau",
    en: "Palau",
    flag: "🇵🇼",
    iso2: "PW",
    iso3: "PLW",
  },
  {
    de: "Papua-Neuguinea",
    es: "Papúa Nueva Guinea",
    en: "Papua New Guinea",
    flag: "🇵🇬",
    iso2: "PG",
    iso3: "PNG",
  },
  {
    de: "Polen",
    es: "Polonia",
    en: "Poland",
    flag: "🇵🇱",
    iso2: "PL",
    iso3: "POL",
  },
  {
    de: "Puerto Rico",
    es: "Puerto Rico",
    en: "Puerto Rico",
    flag: "🇵🇷",
    iso2: "PR",
    iso3: "PRI",
  },
  {
    de: "Nordkorea",
    es: "Corea del Norte",
    en: "North Korea",
    flag: "🇰🇵",
    iso2: "KP",
    iso3: "PRK",
  },
  {
    de: "Portugal",
    es: "Portugal",
    en: "Portugal",
    flag: "🇵🇹",
    iso2: "PT",
    iso3: "PRT",
  },
  {
    de: "Paraguay",
    es: "Paraguay",
    en: "Paraguay",
    flag: "🇵🇾",
    iso2: "PY",
    iso3: "PRY",
  },
  {
    de: "Palästina",
    es: "Palestina",
    en: "Palestine",
    flag: "🇵🇸",
    iso2: "PS",
    iso3: "PSE",
  },
  {
    de: "Französisch-Polynesien",
    es: "Polinesia Francesa",
    en: "French Polynesia",
    flag: "🇵🇫",
    iso2: "PF",
    iso3: "PYF",
  },
  {
    de: "Katar",
    es: "Catar",
    en: "Qatar",
    flag: "🇶🇦",
    iso2: "QA",
    iso3: "QAT",
  },
  {
    de: "Réunion",
    es: "Reunión",
    en: "Réunion",
    flag: "🇷🇪",
    iso2: "RE",
    iso3: "REU",
  },
  {
    de: "Rumänien",
    es: "Rumania",
    en: "Romania",
    flag: "🇷🇴",
    iso2: "RO",
    iso3: "ROU",
  },
  {
    de: "Russland",
    es: "Rusia",
    en: "Russia",
    flag: "🇷🇺",
    iso2: "RU",
    iso3: "RUS",
  },
  {
    de: "Ruanda",
    es: "Ruanda",
    en: "Rwanda",
    flag: "🇷🇼",
    iso2: "RW",
    iso3: "RWA",
  },
  {
    de: "Saudi-Arabien",
    es: "Arabia Saudí",
    en: "Saudi Arabia",
    flag: "🇸🇦",
    iso2: "SA",
    iso3: "SAU",
  },
  {
    de: "Sudan",
    es: "Sudán",
    en: "Sudan",
    flag: "🇸🇩",
    iso2: "SD",
    iso3: "SDN",
  },
  {
    de: "Senegal",
    es: "Senegal",
    en: "Senegal",
    flag: "🇸🇳",
    iso2: "SN",
    iso3: "SEN",
  },
  {
    de: "Singapur",
    es: "Singapur",
    en: "Singapore",
    flag: "🇸🇬",
    iso2: "SG",
    iso3: "SGP",
  },
  {
    de: "Südgeorgien und die Südlichen Sandwichinseln",
    es: "Islas Georgias del Sur y Sandwich del Sur",
    en: "South Georgia",
    flag: "🇬🇸",
    iso2: "GS",
    iso3: "SGS",
  },
  {
    de: "Spitzbergen und Jan Mayen",
    es: "Islas Svalbard y Jan Mayen",
    en: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    iso2: "SJ",
    iso3: "SJM",
  },
  {
    de: "Salomonen",
    es: "Islas Salomón",
    en: "Solomon Islands",
    flag: "🇸🇧",
    iso2: "SB",
    iso3: "SLB",
  },
  {
    de: "Sierra Leone",
    es: "Sierra Leone",
    en: "Sierra Leone",
    flag: "🇸🇱",
    iso2: "SL",
    iso3: "SLE",
  },
  {
    de: "El Salvador",
    es: "El Salvador",
    en: "El Salvador",
    flag: "🇸🇻",
    iso2: "SV",
    iso3: "SLV",
  },
  {
    de: "San Marino",
    es: "San Marino",
    en: "San Marino",
    flag: "🇸🇲",
    iso2: "SM",
    iso3: "SMR",
  },
  {
    de: "Somalia",
    es: "Somalia",
    en: "Somalia",
    flag: "🇸🇴",
    iso2: "SO",
    iso3: "SOM",
  },
  {
    de: "St. Pierre und Miquelon",
    es: "San Pedro y Miquelón",
    en: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    iso2: "PM",
    iso3: "SPM",
  },
  {
    de: "Serbien",
    es: "Serbia",
    en: "Serbia",
    flag: "🇷🇸",
    iso2: "RS",
    iso3: "SRB",
  },
  {
    de: "Südsudan",
    es: "Sudán del Sur",
    en: "South Sudan",
    flag: "🇸🇸",
    iso2: "SS",
    iso3: "SSD",
  },
  {
    de: "São Tomé und Príncipe",
    es: "Santo Tomé y Príncipe",
    en: "São Tomé and Príncipe",
    flag: "🇸🇹",
    iso2: "ST",
    iso3: "STP",
  },
  {
    de: "Suriname",
    es: "Surinam",
    en: "Suriname",
    flag: "🇸🇷",
    iso2: "SR",
    iso3: "SUR",
  },
  {
    de: "Slowakei",
    es: "República Eslovaca",
    en: "Slovakia",
    flag: "🇸🇰",
    iso2: "SK",
    iso3: "SVK",
  },
  {
    de: "Slowenien",
    es: "Eslovenia",
    en: "Slovenia",
    flag: "🇸🇮",
    iso2: "SI",
    iso3: "SVN",
  },
  {
    de: "Schweden",
    es: "Suecia",
    en: "Sweden",
    flag: "🇸🇪",
    iso2: "SE",
    iso3: "SWE",
  },
  {
    de: "Swasiland",
    es: "Suazilandia",
    en: "Eswatini",
    flag: "🇸🇿",
    iso2: "SZ",
    iso3: "SWZ",
  },
  {
    de: "Sint Maarten",
    es: "Sint Maarten",
    en: "Sint Maarten",
    flag: "🇸🇽",
    iso2: "SX",
    iso3: "SXM",
  },
  {
    de: "Seychellen",
    es: "Seychelles",
    en: "Seychelles",
    flag: "🇸🇨",
    iso2: "SC",
    iso3: "SYC",
  },
  {
    de: "Syrien",
    es: "Siria",
    en: "Syria",
    flag: "🇸🇾",
    iso2: "SY",
    iso3: "SYR",
  },
  {
    de: "Turks-und Caicosinseln",
    es: "Islas Turks y Caicos",
    en: "Turks and Caicos Islands",
    flag: "🇹🇨",
    iso2: "TC",
    iso3: "TCA",
  },
  {
    de: "Tschad",
    es: "Chad",
    en: "Chad",
    flag: "🇹🇩",
    iso2: "TD",
    iso3: "TCD",
  },
  {
    de: "Togo",
    es: "Togo",
    en: "Togo",
    flag: "🇹🇬",
    iso2: "TG",
    iso3: "TGO",
  },
  {
    de: "Thailand",
    es: "Tailandia",
    en: "Thailand",
    flag: "🇹🇭",
    iso2: "TH",
    iso3: "THA",
  },
  {
    de: "Tadschikistan",
    es: "Tayikistán",
    en: "Tajikistan",
    flag: "🇹🇯",
    iso2: "TJ",
    iso3: "TJK",
  },
  {
    de: "Tokelau",
    es: "Islas Tokelau",
    en: "Tokelau",
    flag: "🇹🇰",
    iso2: "TK",
    iso3: "TKL",
  },
  {
    de: "Turkmenistan",
    es: "Turkmenistán",
    en: "Turkmenistan",
    flag: "🇹🇲",
    iso2: "TM",
    iso3: "TKM",
  },
  {
    de: "Osttimor",
    es: "Timor Oriental",
    en: "Timor-Leste",
    flag: "🇹🇱",
    iso2: "TL",
    iso3: "TLS",
  },
  {
    de: "Tonga",
    es: "Tonga",
    en: "Tonga",
    flag: "🇹🇴",
    iso2: "TO",
    iso3: "TON",
  },
  {
    de: "Trinidad und Tobago",
    es: "Trinidad y Tobago",
    en: "Trinidad and Tobago",
    flag: "🇹🇹",
    iso2: "TT",
    iso3: "TTO",
  },
  {
    de: "Tunesien",
    es: "Túnez",
    en: "Tunisia",
    flag: "🇹🇳",
    iso2: "TN",
    iso3: "TUN",
  },
  {
    de: "Türkei",
    es: "Turquía",
    en: "Turkey",
    flag: "🇹🇷",
    iso2: "TR",
    iso3: "TUR",
  },
  {
    de: "Tuvalu",
    es: "Tuvalu",
    en: "Tuvalu",
    flag: "🇹🇻",
    iso2: "TV",
    iso3: "TUV",
  },
  {
    de: "Taiwan",
    es: "Taiwán",
    en: "Taiwan",
    flag: "🇹🇼",
    iso2: "TW",
    iso3: "TWN",
  },
  {
    de: "Tansania",
    es: "Tanzania",
    en: "Tanzania",
    flag: "🇹🇿",
    iso2: "TZ",
    iso3: "TZA",
  },
  {
    de: "Uganda",
    es: "Uganda",
    en: "Uganda",
    flag: "🇺🇬",
    iso2: "UG",
    iso3: "UGA",
  },
  {
    de: "Ukraine",
    es: "Ucrania",
    en: "Ukraine",
    flag: "🇺🇦",
    iso2: "UA",
    iso3: "UKR",
  },
  {
    de: "Kleinere Inselbesitzungen der Vereinigten Staaten",
    es: "Islas Ultramarinas Menores de Estados Unidos",
    en: "United States Minor Outlying Islands",
    flag: "🇺🇲",
    iso2: "UM",
    iso3: "UMI",
  },
  {
    de: "Uruguay",
    es: "Uruguay",
    en: "Uruguay",
    flag: "🇺🇾",
    iso2: "UY",
    iso3: "URY",
  },
  {
    de: "Vereinigte Staaten",
    es: "Estados Unidos",
    en: "United States",
    flag: "🇺🇸",
    iso2: "US",
    iso3: "USA",
  },
  {
    de: "Usbekistan",
    es: "Uzbekistán",
    en: "Uzbekistan",
    flag: "🇺🇿",
    iso2: "UZ",
    iso3: "UZB",
  },
  {
    de: "Vatikanstadt",
    es: "Ciudad del Vaticano",
    en: "Vatican City",
    flag: "🇻🇦",
    iso2: "VA",
    iso3: "VAT",
  },
  {
    de: "St. Vincent und die Grenadinen",
    es: "San Vicente y Granadinas",
    en: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    iso2: "VC",
    iso3: "VCT",
  },
  {
    de: "Venezuela",
    es: "Venezuela",
    en: "Venezuela",
    flag: "🇻🇪",
    iso2: "VE",
    iso3: "VEN",
  },
  {
    de: "Britische Jungferninseln",
    es: "Islas Vírgenes del Reino Unido",
    en: "British Virgin Islands",
    flag: "🇻🇬",
    iso2: "VG",
    iso3: "VGB",
  },
  {
    de: "Amerikanische Jungferninseln",
    es: "Islas Vírgenes de los Estados Unidos",
    en: "United States Virgin Islands",
    flag: "🇻🇮",
    iso2: "VI",
    iso3: "VIR",
  },
  {
    de: "Vietnam",
    es: "Vietnam",
    en: "Vietnam",
    flag: "🇻🇳",
    iso2: "VN",
    iso3: "VNM",
  },
  {
    de: "Vanuatu",
    es: "Vanuatu",
    en: "Vanuatu",
    flag: "🇻🇺",
    iso2: "VU",
    iso3: "VUT",
  },
  {
    de: "Wallis und Futuna",
    es: "Wallis y Futuna",
    en: "Wallis and Futuna",
    flag: "🇼🇫",
    iso2: "WF",
    iso3: "WLF",
  },
  {
    de: "Samoa",
    es: "Samoa",
    en: "Samoa",
    flag: "🇼🇸",
    iso2: "WS",
    iso3: "WSM",
  },
  {
    de: "Jemen",
    es: "Yemen",
    en: "Yemen",
    flag: "🇾🇪",
    iso2: "YE",
    iso3: "YEM",
  },
  {
    de: "Südafrika",
    es: "República de Sudáfrica",
    en: "South Africa",
    flag: "🇿🇦",
    iso2: "ZA",
    iso3: "ZAF",
  },
  {
    de: "Sambia",
    es: "Zambia",
    en: "Zambia",
    flag: "🇿🇲",
    iso2: "ZM",
    iso3: "ZMB",
  },
  {
    de: "Simbabwe",
    es: "Zimbabue",
    en: "Zimbabwe",
    flag: "🇿🇼",
    iso2: "ZW",
    iso3: "ZWE",
  },
];
