export const styles = {
  page: { background: "#EDEEF3", minHeight: "100vh" },
  verticalFlex: { display: "flex", flexDirection: "column" },
  mainContainer: {
    display: "flex",
    flexDirection: "column",
    margin: "32px auto 0px auto",
    width: "70%",
  },
  titleSectionContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
  },
  titleContainer: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: "28px",
    lineHeight: "32px",
    color: "#1A262D",
    marginTop: "14px",
  },
  subtitleContainer: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "28px",
    color: "#6B7280",
    marginTop: "16px",
    width: "80%",
    textAlign: "center",
    marginBottom: "10px",
  },
  badge: { margin: "16px 0 0 10px" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  midSection: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "40px",
  },
  midSectionTitle: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
    color: "#1A262D",
  },
  title: { display: "flex", marginTop: "10px", marginLeft: "10px" },
  searchContainer: { display: "flex", height: "40px" },
  search: { marginTop: "0px", width: "300px" },
  settingsIcon: {
    border: "solid 1px #D7DBE0",
    borderRadius: "8px",
    marginLeft: "14px",
  },
  bottomSection: {
    display: "flex",
    flexWrap: "wrap",
    marginTop: "10px",
    marginBottom: "40px",
  },
  card: {
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
    alignItems: "stretch",
  },
  cardContainer: {
    background: "white",
    padding: "14px",
    marginLeft: "10px",
    borderRadius: "8px",
    marginTop: "10px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    flex: 1,
  },
  cardTitle: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
    color: "#3E4856",
  },
  cardDescription: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#6B7280",
  },
  cardFooter: {
    marginTop: "2rem",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  footerText: {
    display: "flex",
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#1A262D",
    marginTop: "8px",
  },
  perUse: { color: "#6A7381", fontWeight: 500 },
  useItButton: {
    maxWidth: "208px",
    maxHeight: "40px",
  },
  image: { borderRadius: "8px", maxWidth: "100%", marginBottom: "1rem" },
};
