export const selectedBlue = "#1F75FF";
export const selectedLightBlue = "#E2EEFD";
export const gray = "#3E4856";

const getBackground = (logo, logoName, selectedLightBlue) =>
  `${logo === logoName ? selectedLightBlue : "white"}`;
const getLogoBorder = (logo, logoName) =>
  `1px solid ${logo === logoName ? selectedBlue : gray}`;

export const styles = {
  mainContainer: { background: "#EDEEF3", paddingBottom: "32px" },
  container: {
    background: "#EDEEF3",
    minHeight: "100vh",
    width: "55%",
    margin: "32px auto",
  },
  verticalFlex: { display: "flex", flexDirection: "column" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  titleContainer: {
    display: "flex",
    flexDirection: "column",
    marginLeft: "14px",
  },
  headerTitle: {
    font: "Inter",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
    color: "#1A262D",
  },
  headerSubtitle: {
    font: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#6A7381",
  },
  arrowBack: {
    border: "solid 1px #D7DBE0",
    borderRadius: "8px",
  },
  sectionContainer: {
    background: "white",
    padding: "24px 20px",
    marginTop: "24px",
    borderRadius: "8px",
  },
  workspaceName: { marginTop: "3px", width: "100%" },
  templatesContainer: {
    display: "flex",
    paddingTop: "10px",
    flexWrap: "wrap",
    borderRadius: "8px",
  },
  logoTitle: {
    font: "Inter",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#6A7381",
  },
  logoContainer: {},
  logo: (selectedLogo, logoName) => ({
    padding: "10px 10px 4px 10px",
    border: getLogoBorder(selectedLogo, logoName, selectedBlue),
    borderRadius: "8px",
    cursor: "pointer",
    background: getBackground(selectedLogo, logoName, selectedLightBlue),
    marginLeft: "10px",
    marginBottom: "10px",
  }),
  uploadButton: {
    marginLeft: "16px",
    width: "151px",
    fontSize: "12px",
    font: "Inter",
    textTransform: "none",
    borderRadius: "8px",
  },
  uploadInfo: {
    font: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "14px",
    color: "#9097AC",
    margin: "10px 0px 5px 16px",
  },
  selectedLogoContainer: {
    width: "56px",
    height: "56px",
    padding: "10px 10px 4px 10px",
    borderRadius: "8px",
    cursor: "pointer",
    marginLeft: "10px",
    marginBottom: "10px",
    marginTop: "10px",
  },
  templatesTitle: {
    font: "Inter",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#6A7381",
    margin: "15px 0px 0 10px",
  },
  bigLogoContainer: {
    marginTop: "10px",
    border: "1px solid #EDEEF3",
    borderRadius: "8px",
  },
  dividerContainer: {
    display: "flex",
    justifyContent: "space-between",
    borderBottom: "1px solid #EDEEF3",
  },
  vertical: { display: "flex", flexDirection: "column" },
  colorsContainer: { display: "flex", margin: "10px 10px" },
  membersHeader: {
    padding: "4px",
    display: "flex",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  membersTitle: {
    font: "Inter",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
    color: "#1A262D",
    marginTop: "6px",
  },
  membersRightSection: {
    justifyContent: "space-between",
    display: "flex",
    flexWrap: "wrap",
  },
  sendInviteButton: {
    height: "56px",
    width: "151px",
    font: "Inter",
    textTransform: "none",
    borderRadius: "8px",
    marginLeft: "12px",
  },
  emailInput: { marginTop: "1px", minWidth: "300px", width: "70%" },
  membersContainer: {
    display: "flex",
    flexDirection: "column",
  },
  memberName: {
    font: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#1A262D",
    display: "flex",
    flexDirection: "column",
    minWidth: "220px",
    marginLeft: "10px",
  },
  memberContainer: {
    display: "flex",
    justifyContent: "space-between",
    paddingBottom: "14px",
    paddingTop: "14px",
    flexWrap: "wrap",
  },
  avatar: {},
  invitedSpan: { color: "#9CA5AF", marginRight: "5px" },
  invited: {
    font: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    color: "#1A262D",
    display: "flex",
    minWidth: "150px",
    marginTop: "9px",
  },
  role: { display: "flex" },
  roleSelect: {
    borderRadius: "8px",
    width: "142px",
    height: "32px",
  },
  bin: { marginLeft: "15px", marginTop: "-3px" },
};
